#!/bin/bash
MOS_ACCESS=~/workspace/mos_access/B.com/

if [ $# -lt 2 ]; then
    echo "No enough args"
    exit 1
else
	if [[ $2 == "mosk" || $2 == "mcc" ]]; then
		export KUBECONFIG=$MOS_ACCESS/$1/$2.kubeconfig
		#export PS1="\[\e[41m\]$1\[\e[m\] $PS1"
        #export PS1="\w \[\e[41m\]($1 $2)\[\e[m\] \$ "
        #export PS1="\w ($1 $2) \$ "
        #export PS1="\w \[\e[41m\]($1 $2)\[\e[m\] \$ "
        #PS1="%{$fg[white]%}%n%{$reset_color%}@%{$fg[white]%}%m %{$fg[yellow]%} %{$bg[red]%}%~ [⚠️  PRODUCTION ⚠️ ] %{$reset_color%}%% "
        #PS1="%{$fg[white]%}%n%{$reset_color%}@%{$fg[white]%}%m %{$fg[yellow]%} %{$bg[red]%}%~ [⚠️  PRODUCTION - $1 ⚠️ ] %{$reset_color%}%% "
        PS1="%{$fg[yellow]%} %{$bg[red]%} [⚠️  PRODUCTION - $1 - $2 ⚠️ ] %{$reset_color%} %{$fg[white]%}%n%{$reset_color%}@%{$fg[white]%}%m %~ %% "



	else
		echo "2nd arg must be mosk or mcc"
    	exit 1
	fi

fi
