#!/bin/bash
MOS_ACCESS=~/workspace/mos_access/B.com/

if [ $# -lt 1 ]; then
    echo "No enough args"
    exit 1
else
        if [[ "$1" == *"dev"* ]] || [[ "$1" == *"staging"* ]]; then
            PS1="%{$fg[white]%} %{$bg[cyan]%} [$1 - $2] %{$reset_color%} %{$fg[white]%}%n%{$reset_color%}@%{$fg[white]%}%m %~ %% "
        else
            PS1="%{$fg[yellow]%} %{$bg[red]%} [⚠️  PRODUCTION - $1 - $2 ⚠️ ] %{$reset_color%} %{$fg[white]%}%n%{$reset_color%}@%{$fg[white]%}%m %~ %% "
        fi
        cloud_region_name="$( echo $1| cut -d- -f2 | tr '_' '-' )"
        kubectl config set-context --cluster "$1" --current
        if [[ "$1" == *"mosk"* ]]; then 
            eval $(bkos-creds --region $cloud_region_name --project admin --env)
        fi
        cd $MOS_ACCESS/eu-${cloud_region_name}

fi
