#!/bin/bash
MOS_ACCESS=~/workspace/mos_access/B.com/

if [ $# -lt 1 ]; then
    echo "No enough args"
    exit 1
else
    if [[ "$1" == *"dev"* ]] || [[ "$1" == *"staging"* ]]; then
        if [ -n "$ZSH_VERSION" ] ; then
            PS1="%{$fg[white]%} %{$bg[cyan]%} ($1) %{$reset_color%} %{$fg[white]%}%n%{$reset_color%}@%{$fg[white]%}%m %~ %% "
        else
            PS1="\w \[\e[36m\]($1)\[\e[m\] \$ "
        fi
    else
        if [ -n "$ZSH_VERSION" ] ; then
            PS1="%{$fg[yellow]%} %{$bg[red]%} (⚠️  PRODUCTION - $1 ⚠️ ) %{$reset_color%} %{$fg[white]%}%n%{$reset_color%}@%{$fg[white]%}%m %~ %% "
        else
            PS1="\w \[\e[41m\](PRODUCTION - $1)\[\e[m\] \$ "
        fi

    fi
    cloud_region_name="$( echo $1| cut -d- -f2 | tr '_' '-' )"
    #kubectl config use-context "$1"
    kubectl_path="$(which kubectl)"
    alias kubectl="$kubectl_path --context $1"
    alias k="$kubectl_path --context $1"
#    if [[ "$1" == *"mosk"* ]]; then 
#        eval $(bkos-creds --region $cloud_region_name --project admin --env)
#    fi
    cd $MOS_ACCESS/eu-${cloud_region_name}

fi
