apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipmi-thermal-monitoring.fullname" . }}-mon-config
  labels:
  {{- include "ipmi-thermal-monitoring.labels" . | nindent 4 }}
data:
  telegraf.conf: {{ .Values.monConfig.telegrafConf | toYaml | indent 1 }}